const shows=[
 {name:"Black Clover",genre:"Action",year:"Magic • Action",a:"#53305e",desc:"Asta dreams of becoming the Wizard King in a world where magic is everything."},
 {name:"Solo Leveling",genre:"Action",year:"Action • Fantasy",a:"#183d59",desc:"A hunter rises from the weakest to an unimaginable power."},
 {name:"Demon Slayer",genre:"Adventure",year:"Action • Adventure",a:"#753b37",desc:"A young swordsman fights demons to save his sister."},
 {name:"Jujutsu Kaisen",genre:"Action",year:"Dark Fantasy",a:"#34365e",desc:"Curses and sorcerers collide in supernatural battles."},
 {name:"One Piece",genre:"Adventure",year:"Adventure • Comedy",a:"#8a5529",desc:"A pirate crew sails toward the ultimate treasure."},
 {name:"Frieren",genre:"Fantasy",year:"Fantasy • Drama",a:"#365b69",desc:"A mage discovers what a lifetime means after the adventure."}
];
const grid=document.getElementById('animeGrid');
function render(filter='All'){grid.innerHTML='';shows.filter(s=>filter==='All'||s.genre===filter).forEach((s,i)=>{const el=document.createElement('article');el.className='card';el.innerHTML=`<div class="poster" style="--a:${s.a}"><span>ANIME WORLD • ${String(i+1).padStart(2,'0')}</span></div><div class="cardbody"><h3>${s.name}</h3><div class="meta">${s.year}</div><button class="watch">View details ↗</button></div>`;el.querySelector('button').onclick=()=>details(s);grid.appendChild(el)})}
function details(s){const hi=language==='hi';const hindi={"Black Clover":"Asta जादू की दुनिया में Wizard King बनने का सपना देखता है।","Solo Leveling":"एक कमजोर हंटर असाधारण ताकत हासिल करता है।","Demon Slayer":"एक युवा तलवारबाज अपनी बहन को बचाने के लिए राक्षसों से लड़ता है।","Jujutsu Kaisen":"श्राप और जादूगरों के बीच अलौकिक लड़ाइयाँ होती हैं।","One Piece":"समुद्री डाकुओं का दल सबसे बड़े खजाने की खोज में निकलता है।","Frieren":"एक जादूगरनी अपने सफर के बाद जीवन का अर्थ समझती है।"};document.getElementById('modalContent').innerHTML=`<small>${s.genre.toUpperCase()}</small><h2>${s.name}</h2><p>${hi?(hindi[s.name]||s.desc):s.desc}</p><p>${hi?'देखने के लिए नीचे अपने अधिकृत एपिसोड वीडियो का सीधा URL जोड़ें।':'To watch, add your authorized episode video URL in the player section below.'}</p>`;document.getElementById('modal').classList.add('show')}
function closeModal(){document.getElementById('modal').classList.remove('show')}
function showNotice(){document.getElementById('modalContent').innerHTML=language==='hi'?'<h2>Anime World में आपका स्वागत है</h2><p>नीचे कोई anime चुनें या अपने वीडियो का अधिकृत लिंक जोड़ें।</p>':'<h2>Welcome to Anime World</h2><p>Choose an anime below, or paste your own authorized video link in the player section.</p>';document.getElementById('modal').classList.add('show')}
function playCustom(){const u=document.getElementById('videoUrl').value.trim(),v=document.getElementById('player');if(!u){alert('Please paste a video URL first.');return}try{const url=new URL(u);if(!['http:','https:'].includes(url.protocol))throw 0;v.src=u;v.style.display='block';v.play().catch(()=>alert('This link may not be a direct playable video URL.'));}catch(e){alert('Please enter a valid http or https video URL.')}} 
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.filter)});
let language='en';
function setLanguage(){const hi=language==='hi';document.getElementById('langBtn').textContent=hi?'हिंदी / EN':'हिंदी / EN';document.getElementById('heroTag').textContent=hi?'✦ आपकी ANIME दुनिया':'✦ YOUR ANIME UNIVERSE';document.getElementById('heroTitle').innerHTML=hi?'अपनी<br><span>Anime World.</span>':'Enter the<br><span>Anime World.</span>';document.getElementById('heroDesc').textContent=hi?'अनगिनत रोमांच, शानदार लड़ाइयाँ और आपकी अगली पसंदीदा कहानी।':'Unlimited adventures. Legendary battles. Your next obsession starts here.';document.getElementById('exploreBtn').innerHTML=(hi?'Anime देखें':'Explore Anime')+' <b>→</b>';document.getElementById('trendLabel').textContent=hi?'आपके लिए चुना गया':'HANDPICKED FOR YOU';document.getElementById('trendTitle').textContent=hi?'लोकप्रिय Anime':'Trending Anime';document.getElementById('playerLabel').textContent=hi?'अपनी कहानी जारी रखें':'CONTINUE YOUR JOURNEY';document.getElementById('playerTitle').textContent=hi?'अपने लिंक से देखें':'Watch with your links';document.getElementById('playerHelp').textContent=hi?'एपिसोड चलाने के लिए अपना वीडियो URL जोड़ें।':'Add your own video URL to play an episode.';document.getElementById('videoUrl').placeholder=hi?'अपना वीडियो URL डालें (MP4 लिंक)':'Paste your video URL (MP4 link)';document.getElementById('playBtn').textContent=hi?'वीडियो चलाएँ':'Play video';document.querySelectorAll('nav button').forEach(b=>b.textContent=hi?b.dataset.hi:b.dataset.en);}
document.getElementById('langBtn').onclick=()=>{language=language==='en'?'hi':'en';setLanguage();};
render();
